# Generated by Django 6.0.6 on 2026-06-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_name', models.CharField(max_length=500)),
                ('API_Method', models.CharField(max_length=500)),
                ('API_use', models.CharField(max_length=500)),
                ('Start_time', models.DateTimeField()),
                ('Status', models.CharField(max_length=500)),
                ('End_time', models.DateTimeField()),
                ('Duration', models.CharField(max_length=500)),
            ],
        ),
    ]
